[package]
name = "tetris"
version = "0.1.0"
authors = ["andrei"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
stackvec = "0.2.1"
rand = "0.7.3"
