[package]
name = "tetris"
version = "0.1.0"
authors = ["andrei"]
edition = "2021"

[dependencies]
sdl2 = "0.35.2"
rand = "0.8.5"
arrayvec = "0.7.2"
strum = { version = "0.24.1", features = ["derive"] }
